config/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('todo.urls'))
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete')
]

todo/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    title = models.CharField(max_length=300)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.title

todo/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from .models import Todo
# Create your views here.

def index(request):
    todos = Todo.objects.all()
    return render(request, 'index.html', context={'todos': todos})

def create(request):
    if request.method != 'POST':
        return JsonResponse({'message': 'this page just allow post method'})
    title = request.POST['title']
    Todo.objects.create(title=title, status=False)
    return redirect('todo:index')

def update(request, id):
    try:
        todo = Todo.objects.get(id=id)
    except:
        return JsonResponse({'message': f'the object with id {id} not found'})
    todo.status = not todo.status
    todo.save()
    return redirect('todo:index')

def delete(request, id):
    try:
        todo = Todo.objects.get(id=id)
    except:
        return JsonResponse({'message': f'the object with id {id} not found'})
    
    todo.delete()
    return redirect('todo:index')

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <form id="myForm" class="header" method="post" action="{% url 'todo:create' %}">
        {% csrf_token %}
        <h2>My To Do List</h2>
        <input type="text" id="myInput" name="title" placeholder="Title...">
        <!-- <span onclick="newElement()" class="addBtn">Add</span> -->
        <input type="submit" class="addBtn" value="Add">
    </form>
    
    <ul id="myUL">
        {% for todo in todos %}
            <li class="{% if todo.status %}checked{% endif %}">
                <a class="title" href="{% url 'todo:update' todo.id %}">{{ todo.title }}</a>
                <a class="removeLink" href="{% url 'todo:delete' todo.id %}">remove</a>
            </li>
        {% endfor %}
    </ul>
    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>